---
- name: Create S3
  hosts: localhost
  connection: local
  become: true

  vars_prompt:
     - name: bucket_name
       prompt: "Enter the bucket name: "
       private: false

     - name: aws_profile
       prompt: "Enter the aws profile: "
       private: false

  tasks: 
  - name: Create S3 bucket
    amazon.aws.s3_bucket:
      profile: "{{ aws_profile }}"
      name: "{{ bucket_name }}"
      state: present
...
